spring.application.name=thermomarket-api
spring.profiles.active=${APP_PROFILE:local}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

s3.bucket-name=${S3_BUCKET_NAME:}
s3.region=${S3_REGION:us-east-1}
s3.public-base-url=${S3_PUBLIC_BASE_URL:}

server.error.include-message=always
server.error.include-binding-errors=always

springdoc.swagger-ui.path=/swagger-ui.html
